name: Build-Client

on: [push, pull_request]

jobs:
    build:
        name: Build Win

        runs-on: windows-latest

        steps:
        - uses: actions/checkout@v1
          with:
            submodules: 'recursive'
            
        - name: Build APCpp
          run: |
            mkdir SWR_AP_Client\external\APCpp\build
            cd SWR_AP_Client\external\APCpp\build
            cmake -G "Visual Studio 17 2022" -A Win32 `
              -DUSE_ZLIB=OFF `
              -DCMAKE_BUILD_TYPE=Release ..
            cmake --build . --config Release
            
        - name: Move APCpp for linking/copying
          run: |
            cd ..
            mkdir SWR_AP_Client\SWR_AP_Client\external\APCpp\out\build\x86-Release
            copy SWR_AP_Client\SWR_AP_Client\external\APCpp\build\Release\APCpp.dll SWR_AP_Client\SWR_AP_Client\external\APCpp\out\build\x86-Release
            copy SWR_AP_Client\SWR_AP_Client\external\APCpp\build\Release\APCpp.lib SWR_AP_Client\SWR_AP_Client\external\APCpp\out\build\x86-Release
        
        - name: Add msbuild
          uses: microsoft/setup-msbuild@v2

        - name: Build Client
          run: |
            ls
            msbuild SWR_AP_Client.sln /p:Configuration=Release /p:Platform="x86"
            ls

        - name: Create artifact
          uses: actions/upload-artifact@v3
          with: 
            name: SWR_AP_Client
            path: |
              dist\*
